export interface SubChapter {
  id: string;
  title: string;
  points: number;
}

export interface Chapter {
  id: string;
  title: string;
  subChapters: SubChapter[];
}

export const developmentNotes: Chapter[] = [
  {
    id: 'chapter-1',
    title: 'Chapter 1: Foundation & Setup',
    subChapters: [
      { id: '1.1', title: 'What is Web Development?', points: 10 },
      { id: '1.2', title: 'Client-Server Architecture', points: 10 },
      { id: '1.3', title: 'Frontend vs Backend vs Full Stack', points: 10 },
      { id: '1.4', title: 'Introduction to the MERN Stack', points: 10 },
      { id: '1.5', title: 'Development Environment Setup', points: 10 },
      { id: '1.6', title: 'Code Editors & Extensions', points: 10 },
      { id: '1.7', title: 'Terminal/Command Line Basics', points: 10 },
    ],
  },
  {
    id: 'chapter-2',
    title: 'Chapter 2: Version Control with Git & GitHub',
    subChapters: [
      { id: '2.1', title: 'Introduction to Version Control', points: 10 },
      { id: '2.2', title: 'Git Installation & Configuration', points: 10 },
      { id: '2.3', title: 'Git Basics (Init, Add, Commit, Status, Log)', points: 10 },
      { id: '2.4', title: 'Working with Branches & Merging', points: 10 },
      { id: '2.5', title: 'GitHub Introduction & Account Setup', points: 10 },
      { id: '2.6', title: 'Remote Repositories (Push, Pull, Clone, Fetch)', points: 10 },
      { id: '2.7', title: 'Collaboration Workflows (Forks, Pull Requests, Issues)', points: 10 },
      { id: '2.8', title: 'Git Best Practices & .gitignore', points: 10 },
    ],
  },
  {
    id: 'chapter-3',
    title: 'Chapter 3: Frontend Fundamentals',
    subChapters: [
      { id: '3.1', title: 'HTML5 Essentials & Semantic Elements', points: 10 },
      { id: '3.2', title: 'HTML Complete Guide', points: 10 },
      { id: '3.3', title: 'CSS3 Complete Guide', points: 10 },
      { id: '3.4', title: 'CSS Layout (Flexbox & Grid)', points: 10 },
      { id: '3.5', title: 'CSS Animations & Transitions', points: 10 },
      { id: '3.6', title: 'Responsive Design & Media Queries', points: 10 },
      { id: '3.7', title: 'CSS Preprocessors (Sass/SCSS)', points: 10 },
      { id: '3.8', title: 'Browser Developer Tools', points: 10 },
    ],
  },
  {
    id: 'chapter-4',
    title: 'Chapter 4: JavaScript Fundamentals',
    subChapters: [
      { id: '4.1', title: 'JavaScript Basics (Variables, Data Types, Operators)', points: 10 },
      { id: '4.2', title: 'Control Structures (Conditionals, Loops)', points: 10 },
      { id: '4.3', title: 'Functions & Scope', points: 10 },
      { id: '4.4', title: 'Arrays & Array Methods', points: 10 },
      { id: '4.5', title: 'Objects & Object Methods', points: 10 },
      { id: '4.6', title: 'DOM Manipulation & Events', points: 10 },
      { id: '4.7', title: 'ES6+ Features (Arrow Functions, Destructuring, Modules)', points: 10 },
      { id: '4.8', title: 'Asynchronous JavaScript (Promises, Async/Await)', points: 10 },
      { id: '4.9', title: 'Error Handling & Debugging', points: 10 },
      { id: '4.10', title: 'Js-MiniProject(Stone,Paper,Scissor)', points: 15 },
      { id: '4.11', title: 'Mini Project Preview', points: 10 },
    ],
  },
  {
    id: 'chapter-5',
    title: 'Chapter 5: CSS Frameworks & UI Libraries',
    subChapters: [
      { id: '5.1', title: 'Introduction to CSS Frameworks', points: 10 },
      { id: '5.2', title: 'Bootstrap Fundamentals', points: 10 },
      { id: '5.3', title: 'Tailwind CSS Setup & Configuration', points: 10 },
      { id: '5.4', title: 'Tailwind CSS Utility Classes', points: 10 },
      { id: '5.5', title: 'Tailwind CSS Responsive Design', points: 10 },
      { id: '5.6', title: 'Tailwind CSS Components & Custom Styles', points: 10 },
      { id: '5.7', title: 'CSS Framework Comparison & Best Practices', points: 10 },
    ],
  },
  {
    id: 'chapter-6',
    title: 'Chapter 6: React.js - Frontend Framework',
    subChapters: [
      { id: '6.1', title: 'Introduction to React & Virtual DOM', points: 10 },
      { id: '6.2', title: 'Create React App & Project Structure', points: 10 },
      { id: '6.3', title: 'JSX Syntax & Components', points: 10 },
      { id: '6.4', title: 'Props & Component Communication', points: 10 },
      { id: '6.5', title: 'State Management with useState', points: 10 },
      { id: '6.6', title: 'Event Handling in React', points: 10 },
      { id: '6.7', title: 'Conditional Rendering & Lists', points: 10 },
      { id: '6.8', title: 'React Hooks (useEffect, useContext, useRef)', points: 10 },
      { id: '6.9', title: 'React Router for Navigation', points: 10 },
      { id: '6.10', title: 'Forms & Form Validation in React', points: 10 },
      { id: '6.11', title: 'Component Lifecycle & Cleanup', points: 10 },
      { id: '6.12', title: 'React Mini Projects', points: 15 },
    ],
  },
  {
    id: 'chapter-7',
    title: 'Chapter 7: Backend Development with Node.js',
    subChapters: [
      { id: '7.1', title: 'Introduction to Node.js & Runtime Environment', points: 10 },
      { id: '7.2', title: 'Node.js Core Modules (fs, path, http, url)', points: 10 },
      { id: '7.3', title: 'npm & Package Management', points: 10 },
      { id: '7.4', title: 'Creating Your First Node.js Server', points: 10 },
      { id: '7.5', title: 'Understanding Modules & Module.exports', points: 10 },
      { id: '7.6', title: 'Asynchronous Programming in Node.js', points: 10 },
      { id: '7.7', title: 'File System Operations', points: 10 },
      { id: '7.8', title: 'Environment Variables & dotenv', points: 10 },
    ],
  },
  {
    id: 'chapter-8',
    title: 'Chapter 8: Express.js - Backend Framework',
    subChapters: [
      { id: '8.1', title: 'Introduction to Express.js', points: 10 },
      { id: '8.2', title: 'Express Setup & Basic Server', points: 10 },
      { id: '8.3', title: 'Routing & Route Parameters', points: 10 },
      { id: '8.4', title: 'Middleware Concepts & Usage', points: 10 },
      { id: '8.5', title: 'Built-in Middleware (express.json, express.static)', points: 10 },
      { id: '8.6', title: 'Custom Middleware Development', points: 10 },
      { id: '8.7', title: 'Request & Response Objects', points: 10 },
      { id: '8.8', title: 'Error Handling Middleware', points: 10 },
      { id: '8.9', title: 'Express Router & Modular Routing', points: 10 },
      { id: '8.10', title: 'Template Engines (EJS, Handlebars)', points: 10 },
    ],
  },
  {
    id: 'chapter-9',
    title: 'Chapter 9: REST API Development',
    subChapters: [
      { id: '9.1', title: 'REST Architecture Principles', points: 10 },
      { id: '9.2', title: 'HTTP Methods & Status Codes', points: 10 },
      { id: '9.3', title: 'API Design Best Practices', points: 10 },
      { id: '9.4', title: 'CRUD Operations Implementation', points: 10 },
      { id: '9.5', title: 'Request Validation & Sanitization', points: 10 },
      { id: '9.6', title: 'API Documentation with Swagger/Postman', points: 10 },
      { id: '9.7', title: 'File Uploads & Handling (Multer)', points: 10 },
      { id: '9.8', title: 'API Versioning Strategies', points: 10 },
      { id: '9.9', title: 'REST API Mini Project', points: 15 },
    ],
  },
  {
    id: 'chapter-10',
    title: 'Chapter 10: MongoDB - Database Layer',
    subChapters: [
      { id: '10.1', title: 'Database Fundamentals (SQL vs NoSQL)', points: 10 },
      { id: '10.2', title: 'MongoDB Introduction & Installation', points: 10 },
      { id: '10.3', title: 'MongoDB Compass & Shell Basics', points: 10 },
      { id: '10.4', title: 'CRUD Operations in MongoDB', points: 10 },
      { id: '10.5', title: 'MongoDB Data Types & Schema Design', points: 10 },
      { id: '10.6', title: 'Mongoose ODM Introduction', points: 10 },
      { id: '10.7', title: 'Mongoose Schemas & Models', points: 10 },
      { id: '10.8', title: 'Data Validation with Mongoose', points: 10 },
      { id: '10.9', title: 'Data Relationships (Referenced & Embedded)', points: 10 },
      { id: '10.10', title: 'Mongoose Middleware & Hooks', points: 10 },
      { id: '10.11', title: 'Indexing & Query Optimization', points: 10 },
      { id: '10.12', title: 'Aggregation Pipeline Basics', points: 10 },
      { id: '10.13', title: 'Database Mini Project', points: 15 },
    ],
  },
  {
    id: 'chapter-11',
    title: 'Chapter 11: Authentication & Authorization',
    subChapters: [
      { id: '11.1', title: 'Authentication vs Authorization Concepts', points: 10 },
      { id: '11.2', title: 'Password Hashing with bcrypt', points: 10 },
      { id: '11.3', title: 'JSON Web Tokens (JWT) Theory', points: 10 },
      { id: '11.4', title: 'JWT Implementation in Node.js', points: 10 },
      { id: '11.5', title: 'User Registration & Login System', points: 10 },
      { id: '11.6', title: 'Protected Routes & Middleware', points: 10 },
      { id: '11.7', title: 'Role-Based Access Control (RBAC)', points: 10 },
      { id: '11.8', title: 'Password Reset & Email Verification', points: 10 },
      { id: '11.9', title: 'OAuth & Third-Party Authentication', points: 10 },
      { id: '11.10', title: 'Security Best Practices', points: 10 },
    ],
  },
  {
    id: 'chapter-12',
    title: 'Chapter 12: Frontend-Backend Integration',
    subChapters: [
      { id: '12.1', title: 'Connecting React to Express API', points: 10 },
      { id: '12.2', title: 'HTTP Clients (Fetch API vs Axios)', points: 10 },
      { id: '12.3', title: 'Handling API Responses & Errors', points: 10 },
      { id: '12.4', title: 'Loading States & User Feedback', points: 10 },
      { id: '12.5', title: 'JWT Authentication in React', points: 10 },
      { id: '12.6', title: 'Protected Routes in React Router', points: 10 },
      { id: '12.7', title: 'Context API for Global State', points: 10 },
      { id: '12.8', title: 'CORS Configuration & Handling', points: 10 },
      { id: '12.9', title: 'Proxy Setup for Development', points: 10 },
      { id: '12.10', title: 'Full MERN Integration: To-Do App', points: 15 },
    ],
  },
  {
    id: 'chapter-13',
    title: 'Chapter 13: Advanced State Management',
    subChapters: [
      { id: '13.1', title: 'State Management Patterns', points: 10 },
      { id: '13.2', title: 'Redux Fundamentals', points: 10 },
      { id: '13.3', title: 'Redux Toolkit (RTK) Setup', points: 10 },
      { id: '13.4', title: 'RTK Query for API Integration', points: 10 },
      { id: '13.5', title: 'Zustand - Lightweight State Management', points: 10 },
      { id: '13.6', title: 'React Query/TanStack Query', points: 10 },
      { id: '13.7', title: 'Choosing the Right State Management Solution', points: 10 },
    ],
  },
  {
    id: 'chapter-14',
    title: 'Chapter 14: Performance Optimization',
    subChapters: [
      { id: '14.1', title: 'React Performance Optimization Techniques', points: 10 },
      { id: '14.2', title: 'React.memo & useMemo', points: 10 },
      { id: '14.3', title: 'useCallback & Performance Hooks', points: 10 },
      { id: '14.4', title: 'Code Splitting & Lazy Loading', points: 10 },
      { id: '14.5', title: 'Bundle Optimization with Webpack', points: 10 },
      { id: '14.6', title: 'Database Query Optimization', points: 10 },
      { id: '14.7', title: 'API Caching Strategies', points: 10 },
      { id: '14.8', title: 'Image Optimization & CDNs', points: 10 },
      { id: '14.9', title: 'Performance Monitoring & Profiling', points: 10 },
    ],
  },
  {
    id: 'chapter-15',
    title: 'Chapter 15: Real-Time Applications',
    subChapters: [
      { id: '15.1', title: 'Introduction to Real-Time Communication', points: 10 },
      { id: '15.2', title: 'WebSockets vs Server-Sent Events', points: 10 },
      { id: '15.3', title: 'Socket.io Server Setup', points: 10 },
      { id: '15.4', title: 'Socket.io Client Integration with React', points: 10 },
      { id: '15.5', title: 'Building a Real-Time Chat Application', points: 15 },
      { id: '15.6', title: 'Room Management & Broadcasting', points: 10 },
      { id: '15.7', title: 'Real-Time Notifications', points: 10 },
      { id: '15.8', title: 'Scaling Real-Time Applications', points: 10 },
    ],
  },
  {
    id: 'chapter-16',
    title: 'Chapter 16: Testing MERN Applications',
    subChapters: [
      { id: '16.1', title: 'Testing Fundamentals & Types', points: 10 },
      { id: '16.2', title: 'Unit Testing with Jest', points: 10 },
      { id: '16.3', title: 'React Testing Library', points: 10 },
      { id: '16.4', title: 'Testing React Components', points: 10 },
      { id: '16.5', title: 'API Testing with Supertest', points: 10 },
      { id: '16.6', title: 'Database Testing Strategies', points: 10 },
      { id: '16.7', title: 'Integration Testing', points: 10 },
      { id: '16.8', title: 'End-to-End Testing with Cypress', points: 10 },
      { id: '16.9', title: 'Test-Driven Development (TDD) Basics', points: 10 },
    ],
  },
  {
    id: 'chapter-17',
    title: 'Chapter 17: Security & Best Practices',
    subChapters: [
      { id: '17.1', title: 'Web Security Fundamentals', points: 10 },
      { id: '17.2', title: 'OWASP Top 10 Vulnerabilities', points: 10 },
      { id: '17.3', title: 'Input Validation & Sanitization', points: 10 },
      { id: '17.4', title: 'SQL Injection & NoSQL Injection Prevention', points: 10 },
      { id: '17.5', title: 'Cross-Site Scripting (XSS) Protection', points: 10 },
      { id: '17.6', title: 'Cross-Site Request Forgery (CSRF) Prevention', points: 10 },
      { id: '17.7', title: 'Rate Limiting & DDoS Protection', points: 10 },
      { id: '17.8', title: 'Helmet.js for Security Headers', points: 10 },
      { id: '17.9', title: 'Data Encryption & Secure Communication', points: 10 },
      { id: '17.10', title: 'Security Auditing & Monitoring', points: 10 },
    ],
  },
  {
    id: 'chapter-18',
    title: 'Chapter 18: Deployment & DevOps',
    subChapters: [
      { id: '18.1', title: 'Deployment Strategies & Environments', points: 10 },
      { id: '18.2', title: 'MongoDB Atlas Setup & Configuration', points: 10 },
      { id: '18.3', title: 'Backend Deployment (Render, Railway, Heroku)', points: 10 },
      { id: '18.4', title: 'Frontend Deployment (Netlify, Vercel)', points: 10 },
      { id: '18.5', title: 'Environment Variables in Production', points: 10 },
      { id: '18.6', title: 'Domain Setup & SSL Certificates', points: 10 },
      { id: '18.7', title: 'CI/CD with GitHub Actions', points: 10 },
      { id: '18.8', title: 'Docker Containerization Basics', points: 10 },
      { id: '18.9', title: 'AWS Deployment Fundamentals', points: 10 },
      { id: '18.10', title: 'Monitoring & Logging in Production', points: 10 },
    ],
  },
  {
    id: 'chapter-19',
    title: 'Chapter 19: Advanced Topics',
    subChapters: [
      { id: '19.1', title: 'GraphQL Introduction & Concepts', points: 10 },
      { id: '19.2', title: 'GraphQL with Apollo Server', points: 10 },
      { id: '19.3', title: 'GraphQL Client with Apollo Client', points: 10 },
      { id: '19.4', title: 'Server-Side Rendering (SSR) with Next.js', points: 10 },
      { id: '19.5', title: 'Static Site Generation (SSG)', points: 10 },
      { id: '19.6', title: 'Progressive Web Apps (PWA)', points: 10 },
      { id: '19.7', title: 'Microservices Architecture Basics', points: 10 },
      { id: '19.8', title: 'API Gateway Concepts', points: 10 },
      { id: '19.9', title: 'Caching Strategies (Redis, Memcached)', points: 10 },
      { id: '19.10', title: 'Message Queues & Background Jobs', points: 10 },
    ],
  },
  {
    id: 'chapter-20',
    title: 'Chapter 20: Capstone Projects',
    subChapters: [
      { id: '20.1', title: 'Project Planning & Requirements Analysis', points: 10 },
      { id: '20.2', title: 'Full-Stack E-Commerce Platform', points: 20 },
      { id: '20.3', title: 'Social Media Application', points: 20 },
      { id: '20.4', title: 'Real-Time Chat Application', points: 20 },
      { id: '20.5', title: 'Blog/CMS Platform', points: 20 },
      { id: '20.6', title: 'Task Management System', points: 20 },
      { id: '20.7', title: 'Learning Management System (LMS)', points: 20 },
      { id: '20.8', title: 'Project Deployment & Presentation', points: 15 },
    ],
  },
];
